
# ######################################################################
# These are automatically adapted when using the -f flag in console call
resultfolder: /mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170216_crossvalidation_spl_abc/
intermedfolder: /mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170216_crossvalidation_spl_abc/intermed/
scriptsfolder: /mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170216_crossvalidation_spl_abc/scripts/
# ######################################################################

# ##################################
# All of these entries are required!
run_remove_small_objects: False
run_compute_feature_images: False
run_find_border_contacts: False
run_compute_paths: False
run_features_of_paths: False
run_random_forest: True
# ##################################

debug: False

createfolders: True
overwriteresults: True


# The random forest definition for multiple source files
# ------------------------------------------------------

# File definitions

intermedfolder_a: '/mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170216_crossvalidation_spl_a_slc_z_train_01_pred_10/intermed/'
intermedfolder_b: '/mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170216_crossvalidation_spl_b_slc_z_train_01_pred_10/intermed/'
intermedfolder_c: '/mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170216_crossvalidation_spl_c_slc_z_train_01_pred_10/intermed/'
featuresfile: 'cremi.features.crop.split_z.h5'
pathlistfile: 'cremi.pathlist.crop.split_z.pkl'

# Random forest definition

random_forest:

    # Predict A0
    'z_train_a_b_c0_predict_c1':
        sources:
            train:
                a: [intermedfolder_a, featuresfile, {skeys: [[z_train1_predict0]]}]
                b: [intermedfolder_b, featuresfile, {skeys: [[z_train0_predict1], [z_train1_predict0]]}]
                c: [intermedfolder_c, featuresfile, {skeys: [[z_train0_predict1], [z_train1_predict0]]}]
            predict: [intermedfolder_a, featuresfile, {skeys: z_predict0}]
            train_pl:
                a: [intermedfolder_a, pathlistfile, {skeys: [[z_train1_predict0]]}]
                b: [intermedfolder_b, pathlistfile, {skeys: [[z_train0_predict1], [z_train1_predict0]]}]
                c: [intermedfolder_c, pathlistfile, {skeys: [[z_train0_predict1], [z_train1_predict0]]}]
            predict_pl: [intermedfolder_a, pathlistfile, {skeys: [[z_predict0]]}]

    # default
    # -------
    default:
        params:
            balance_classes: False
