datafolder: /mnt/localdata02/jhennies/neuraldata/cremi_2016/
resultfolder: /mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170125_plot_undersegm_paths_against_beta/
intermedfolder: /mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170125_plot_undersegm_paths_against_beta/intermed/
scriptsfolder: /mnt/localdata01/jhennies/neuraldata/results/cremi_2016/170125_plot_undersegm_paths_against_beta/scripts/

debug: False

createfolders: True
overwriteresults: True

rawdatafile:    'cremi.splA.train.raw_neurons.crop.split_x.h5'
rawdataname:    'raw'
gtruthfile:     'cremi.splA.train.raw_neurons.crop.split_x.h5'
gtruthname:     'neuron_ids'
gtlargefile:    'cremi.splA.train.gtlarge.crop.split_x.h5'
gtlargename:    'neuron_ids'
probsfile:      'cremi.splA.train.probs.crop.split_x.h5'
probsname:      'data'
segmfile:       'cremi.splA.train.mcseg_betas.crop.split_x.h5'
segmlargefile:  'cremi.splA.train.segmlarge.crop.split_x.h5'
rawfeatsfile:   'cremi.splA.train.rawfeats.crop.split_x.h5'
probsfeatsfile: 'cremi.splA.train.probsfeats.crop.split_x.h5'
segfeatsfile:   'cremi.splA.train.segfeats.crop.split_x.h5'
borderctfile:   'cremi.splA.train.borderct.crop.split_x.h5'
borderctname:   'contacts'
pathsfile:      'cremi.splA.train.paths.crop.split_x.h5'
featuresfile:   'cremi.splA.train.features.crop.split_x.h5'
pathlistfile:   'cremi.splA.train.pathlist.crop.split_x.pkl'

run_remove_small_objects: False
run_compute_feature_images: True
run_find_border_contacts: True
run_compute_paths: False
run_features_of_paths: False
run_random_forest: False

remove_small_objects:
    sources:
        - [datafolder, segmfile]
        - [datafolder, gtruthfile]
    targets:
        - [intermedfolder, segmlargefile]
        - [intermedfolder, gtlargefile]
    kwargs:
        skeys: [~, neuron_ids]
        recursive_search: [False, True]
    bysize: 10000
    relabel: True

compute_feature_images:
    general_params:
        anisotropy: [10, 1, 1]
    sources:
        segmentation: [intermedfolder, segmlargefile, {skeys: [['x', '0'], ['x', '1']]}]
    targets:
        segmentation: [intermedfolder, segfeatsfile]
    features:
        segmentation:
            disttransf:
                params: ~
                func: disttransf
                raw: ~


find_border_contacts:
    sources:
        disttransf: [intermedfolder, segfeatsfile, [disttransf, raw]]
        segmentation: [intermedfolder, segmlargefile]
    skwargs:
        default:
            recursive_search: False
        disttransf:
            recursive_search: True
    target: [intermedfolder, borderctfile]

