datafolder: /mnt/localdata02/jhennies/neuraldata/cremi_2016/
resultfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/170119_avoid_redundant_path_calculation_sample_a_full/
intermedfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/170119_avoid_redundant_path_calculation_sample_a_full/intermed/
scriptsfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/170119_avoid_redundant_path_calculation_sample_a_full/scripts/

debug: True

createfolders: True
overwriteresults: True

rawdatafile:    'cremi.splA.train.raw_neurons.crop.split_x.h5'
rawdataname:    'raw'
gtruthfile:     'cremi.splA.train.raw_neurons.crop.split_x.h5'
gtruthname:     'neuron_ids'
gtlargefile:    'cremi.splA.train.gtlarge.crop.split_x.h5'
gtlargename:    'neuron_ids'
probsfile:      'cremi.splA.train.probs.crop.split_x.h5'
probsname:      'data'
segmfile:       'cremi.splA.train.mcseg_betas.crop.split_x.h5'
segmlargefile:  'cremi.splA.train.segmlarge.crop.split_x.h5'
rawfeatsfile:   'cremi.splA.train.rawfeats.crop.split_x.h5'
probsfeatsfile: 'cremi.splA.train.probsfeats.crop.split_x.h5'
segfeatsfile:   'cremi.splA.train.segfeats.crop.split_x.h5'
borderctfile:   'cremi.splA.train.borderct.crop.split_x.h5'
borderctname:   'contacts'
pathsfile:      'cremi.splA.train.paths.crop.split_x.h5'
featuresfile:   'cremi.splA.train.features.crop.split_x.h5'
pathlistfile:   'cremi.splA.train.pathlist.crop.split_x.pkl'

run_remove_small_objects: True
run_compute_feature_images: True
run_find_border_contacts: False
run_compute_paths: False
run_features_of_paths: False
run_random_forest: False

remove_small_objects:
    sources:
        - [datafolder, segmfile]
        - [datafolder, gtruthfile]
    targets:
        - [intermedfolder, segmlargefile]
        - [intermedfolder, gtlargefile]
    kwargs:
        skeys: [~, neuron_ids]
        recursive_search: [False, True]
    bysize: 10000
    relabel: True

compute_feature_images:
    general_params:
        anisotropy: [10, 1, 1]
    sources:
        rawdata: [datafolder, rawdatafile, raw]
        probs: [datafolder, probsfile, data]
        segmentation: [intermedfolder, segmlargefile]
    skwargs:
        default:
            recursive_search: True
        segmentation:
            recursive_search: False
    targets:
        rawdata: [intermedfolder, rawfeatsfile]
        probs: [intermedfolder, probsfeatsfile]
        segmentation: [intermedfolder, segfeatsfile]
    features:
        rawdata:
            raw: ~
            gauss_2:
                params: [2]
                func: gaussian
            gauss_5:
                params: [5]
                func: gaussian
            gauss_10:
                params: [10]
                func: gaussian
            mag_1:
                params: [1]
                func: gaussian_gradient_magnitude
            mag_5:
                params: [5]
                func: gaussian_gradient_magnitude
            mag_10:
                params: [10]
                func: gaussian_gradient_magnitude
            hess_1:
                params: [1]
                func: hessian_eigenvalues
            hess_5:
                params: [5]
                func: hessian_eigenvalues
            hess_10:
                params: [10]
                func: hessian_eigenvalues
            lapl_1:
                params: [1]
                func: laplacian_of_gaussian
            lapl_5:
                params: [5]
                func: laplacian_of_gaussian
            lapl_10:
                params: [10]
                func: laplacian_of_gaussian
            structen_1_2:
                params: [1, 2]   # [inner_scale, outer_scale]
                func: structure_tensor_eigenvalues
            structen_4_8:
                params: [5, 10]
                func: structure_tensor_eigenvalues
            structen_8_16:
                params: [10, 20]
                func: structure_tensor_eigenvalues

        probs:
            raw: ~
            gauss_2:
                params: [2]
                func: gaussian
            gauss_5:
                params: [5]
                func: gaussian
            gauss_10:
                params: [10]
                func: gaussian
            mag_1:
                params: [1]
                func: gaussian_gradient_magnitude
            mag_5:
                params: [5]
                func: gaussian_gradient_magnitude
            mag_10:
                params: [10]
                func: gaussian_gradient_magnitude
            hess_1:
                params: [1]
                func: hessian_eigenvalues
            hess_5:
                params: [5]
                func: hessian_eigenvalues
            hess_10:
                params: [10]
                func: hessian_eigenvalues
            lapl_1:
                params: [1]
                func: laplacian_of_gaussian
            lapl_5:
                params: [5]
                func: laplacian_of_gaussian
            lapl_10:
                params: [10]
                func: laplacian_of_gaussian
            structen_1_2:
                params: [1, 2]   # [inner_scale, outer_scale]
                func: structure_tensor_eigenvalues
            structen_4_8:
                params: [5, 10]
                func: structure_tensor_eigenvalues
            structen_8_16:
                params: [10, 20]
                func: structure_tensor_eigenvalues

        segmentation:
            disttransf:
                params: ~
                func: disttransf
                raw: ~
                gauss_2:
                    params: [2]
                    func: gaussian
                gauss_5:
                    params: [5]
                    func: gaussian
                gauss_10:
                    params: [10]
                    func: gaussian
                mag_1:
                    params: [1]
                    func: gaussian_gradient_magnitude
                mag_5:
                    params: [5]
                    func: gaussian_gradient_magnitude
                mag_10:
                    params: [10]
                    func: gaussian_gradient_magnitude
                hess_1:
                    params: [1]
                    func: hessian_eigenvalues
                hess_5:
                    params: [5]
                    func: hessian_eigenvalues
                hess_10:
                    params: [10]
                    func: hessian_eigenvalues
                lapl_1:
                    params: [1]
                    func: laplacian_of_gaussian
                lapl_5:
                    params: [5]
                    func: laplacian_of_gaussian
                lapl_10:
                    params: [10]
                    func: laplacian_of_gaussian
                structen_1_2:
                    params: [1, 2]   # [inner_scale, outer_scale]
                    func: structure_tensor_eigenvalues
                structen_4_8:
                    params: [5, 10]
                    func: structure_tensor_eigenvalues
                structen_8_16:
                    params: [10, 20]
                    func: structure_tensor_eigenvalues


find_border_contacts:
    sources:
        disttransf: [intermedfolder, segfeatsfile, [disttransf, raw]]
        segmentation: [intermedfolder, segmlargefile]
    skwargs:
        default:
            recursive_search: False
        disttransf:
            recursive_search: True
    target: [intermedfolder, borderctfile]


compute_paths:

    # Organize settings like this:
    #
    # experiment_0:
    #     truepaths:
    #         sources:
    #             segm: [path, filename, {arguments: vals}]
    #             gt: [path, filename, {arguments: vals}]
    #             conts: [path, filename, {arguments: vals}]
    #             dt: [path, filename, {arguments: vals}]
    #         target: [path, filename]
    #         params:
    #             avoid_duplicates: True|False
    #             penaltypower: value > 0
    #             ignorelabels: []
    #             max_paths_per_object: value >= 1
    #             max_paths_per_object_seed: value
    #     falsepaths:
    #         ...
    #     default:
    #         ...
    # experiment_1:
    #     ...
    # ...
    # experiment_n:
    #     ...
    # default
    #     ...

    'experiment_0a':
        falsepaths:
            params:
                avoid_duplicates: True

    'experiment_1a': ~

    default:
        truepaths:
            sources:
                segm: [intermedfolder, segmlargefile, {skeys: [[x, '0', beta_0.5]]}]
                gt: [intermedfolder, gtlargefile, {skeys: [[x, '0', neuron_ids]]}]
                conts: [intermedfolder, borderctfile, {skeys: [[x, '0', beta_0.5, contacts]]}]
                dt: [intermedfolder, segfeatsfile, {skeys: [[x, '0', beta_0.5, disttransf, raw]]}]
            params:
                max_paths_per_object: 1
        falsepaths:
            sources:
                segm: [intermedfolder, segmlargefile, {skeys: [[x, '0']]}]
                gt: [intermedfolder, gtlargefile, {skeys: [[x, '0', neuron_ids]]}]
                conts: [intermedfolder, borderctfile, {skeys: [[x, '0', '*', contacts]]}]
                dt: [intermedfolder, segfeatsfile, {skeys: [[x, '0', '*', disttransf, raw]]}]
            params:
                max_paths_per_object: ~

        default:
            target: [intermedfolder, pathsfile]
            params:
                avoid_duplicates: False
                penaltypower: 10
                ignorelabels: []
                max_paths_per_object_seed: ~


features_of_paths:

    'experiment_0a':
        sources:
            paths:
                truepaths: [intermedfolder, pathsfile, {skeys: [[experiment_0a, truepaths]]}]
                falsepaths: [intermedfolder, pathsfile, {skeys: [[experiment_0a, falsepaths]]}]
    'experiment_1a':
        sources:
            paths:
                truepaths: [intermedfolder, pathsfile, {skeys: [[experiment_1a, truepaths]]}]
                falsepaths: [intermedfolder, pathsfile, {skeys: [[experiment_1a, falsepaths]]}]

    default:
        sources:
            featureims:
                rawdata: [intermedfolder, rawfeatsfile, {skeys: ~}]
                probs: [intermedfolder, probsfeatsfile, {skeys: ~}]
                segmentation: [intermedfolder, segfeatsfile, {skeys: ~}]
    #        segmentation:
    #            [intermedfolder, segmlargefile, {skeys: ~}]
        targets:
            features: [intermedfolder, featuresfile]
            pathlist: [intermedfolder, pathlistfile]
        params:
            anisotropy: [10, 1, 1]
            features:
                - Sum
                - Mean
                - Variance
                - Maximum
                - Minimum
                - Kurtosis
                - Skewness
                - Pathlength
            max_paths_per_label: 10


random_forest:
    sources:
        0a:
            train: [intermedfolder, featuresfile, {skeys: [x, 0, beta_0.5], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 1, beta_0.5], recursive_search: True}]
            balance_classes: False
        0b:
            train: [intermedfolder, featuresfile, {skeys: [x, 1, beta_0.5], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 0, beta_0.5], recursive_search: True}]
            balance_classes: False
        1a:
            train: [intermedfolder, featuresfile, {skeys: [x, 0], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 1, beta_0.5], recursive_search: True}]
            balance_classes: False
        1b:
            train: [intermedfolder, featuresfile, {skeys: [x, 1], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 0, beta_0.5], recursive_search: True}]
            balance_classes: False
        2a:
            train: [intermedfolder, featuresfile, {skeys: [x, 0], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 1, beta_0.5], recursive_search: True}]
            balance_classes: True
        2b:
            train: [intermedfolder, featuresfile, {skeys: [x, 1], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 0, beta_0.5], recursive_search: True}]
            balance_classes: True
        3a:
            traintrue: [intermedfolder, featuresfile, {skeys: [x, 0, beta_0.5], recursive_search: True}]
            trainfalse: [intermedfolder, featuresfile, {skeys: [x, 0], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 1, beta_0.5], recursive_search: True}]
            balance_classes: False
        3b:
            traintrue: [intermedfolder, featuresfile, {skeys: [x, 1, beta_0.5], recursive_search: True}]
            trainfalse: [intermedfolder, featuresfile, {skeys: [x, 1], recursive_search: True}]
            predict: [intermedfolder, featuresfile, {skeys: [x, 0, beta_0.5], recursive_search: True}]
            balance_classes: False
    targets: [resultfolder, resultfile]
    pathlistin: [intermedfolder, pathlistfile]
    pathlistout: [intermedfolder, pathlistforestfile]