datafolder: /mnt/localdata02/jhennies/neuraldata/cremi_2016/
resultfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161206_neurobioseg_x_seg_beta_0.5/
intermedfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161206_neurobioseg_x_seg_beta_0.5/intermed/
scriptsfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161206_neurobioseg_x_seg_beta_0.5/scripts/

debug: True

createfolders: True
overwriteresults: True

rawdatafile:    'cremi.splA.train.raw_neurons.crop.split_x.h5'
rawdataname:    'raw'
labelsfile:     'cremi.splA.train.raw_neurons.crop.split_x.h5'
labelsname:     'neuron_ids'
probsfile:      'cremi.splA.train.probs.crop.split_x.h5'
probsname:      'data'
largeobjfile:   'cremi.splA.train.raw_neurons.crop.split_x.h5'
largeobjname:   'neuron_ids'
largeobjmfile:  'cremi.splA.train.seg_beta_0.5.crop.split_x.h5'
largeobjmnames:
    - 'labels'
    - 'mergeids_small'
    - 'mergeids_random'
    - 'mergeids_all'
    - 'change_hash'
featureimsfile: 'cremi.splA.train.featureims.crop.split_x.h5'
borderctfile:   'cremi.splA.train.borderct.crop.split_x.h5'
borderctname:   'centroids'
pathsfile:      'cremi.splA.train.paths.crop.split_x.h5'
featuresfile:   'cremi.splA.train.features.crop.split_x.h5'
resultsfile:    'cremi.splA.train.results.crop.split_x.h5'
resultsnames:
    - 'random_forest'
    - 'mil'

run_remove_small_objects: False
run_merge_adjacent_objects: False
run_compute_feature_images: False
run_find_border_contacts: False
run_compute_paths: True
run_features_of_paths: True
run_random_forest: True

remove_small_objects:
    bysize: 10000
    relabel: True

merge_adjacent_objects:
    seed: ~
    numberbysize: 0
    numberbyrandom: 100
    algorithm: pairs

compute_feature_images:
    anisotropy: [10, 1, 1]
    features:
        rawdata:
            raw: ~
            gauss_1:
                params: [1]
                func: gaussian
            gauss_3:
                params: [3]
                func: gaussian
            gauss_5:
                params: [5]
                func: gaussian
            gauss_10:
                params: [10]
                func: gaussian
        probs:
            raw: ~
            gauss_1:
                params: [1]
                func: gaussian
            gauss_3:
                params: [3]
                func: gaussian
            gauss_5:
                params: [5]
                func: gaussian
            gauss_10:
                params: [10]
                func: gaussian
        largeobjm:
            disttransf:
                params: ~
                func: disttransf
                raw: ~
                gauss_1:
                    params: [1]
                    func: gaussian
                gauss_3:
                    params: [3]
                    func: gaussian
                gauss_5:
                    params: [5]
                    func: gaussian
                gauss_10:
                    params: [10]
                    func: gaussian

find_border_contacts: ~

compute_paths:
    penaltypower: 10
    ignorelabels: []
    max_end_count: 5
    max_end_count_seed: ~

features_of_paths:
    anisotropy: [10, 1, 1]
    features:
        - Sum
        - Mean
        - Variance
        - Maximum
        - Minimum
        - Kurtosis
        - Skewness
        - Pathlength
    max_paths_per_label: 5

random_forest: ~