datafolder: /mnt/localdata02/jhennies/neuraldata/cremi_2016/
resultfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161128_random_forest_of_paths_add_features_cropped_develop/
intermedfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161128_random_forest_of_paths_add_features_cropped_develop/intermed/
scriptsfolder: /mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161128_random_forest_of_paths_add_features_cropped_develop/scripts/

createfolders: True
overwriteresults: True

rawdatafile:    'cremi.splA.train.raw_neurons.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
rawdataname:    'raw'
labelsfile:     'cremi.splA.train.raw_neurons.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
labelsname:     'neuron_ids'
probsfile:      'cremi.splA.train.probs.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
probsname:      'data'
largeobjfile:   'cremi.splA.train.largeobj.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
largeobjname:   'largeobj'
largeobjmfile:  'cremi.splA.train.largeobjm.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
largeobjmnames:
    - 'largeobjm'
    - 'mergeids_small'
    - 'mergeids_random'
    - 'mergeids_all'
    - 'change_hash'
featureimsfile: 'cremi.splA.train.featureims.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
borderctfile:   'cremi.splA.train.borderct.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
borderctname:   'centroids'
pathstruefile:  'cremi.splA.train.pathstrue.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
pathsfalsefile: 'cremi.splA.train.pathsfalse.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
featuresfile:   'cremi.splA.train.features.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
resultsfile:     'cremi.splA.train.results.crop.crop_x10_110_y200_712_z200_712.split_xyz.h5'
resultsnames:
    - 'random_forest'
    - 'mil'

run_remove_small_objects: True
run_merge_adjacent_objects: True
run_compute_feature_images: True
run_find_border_contacts: True
run_paths_of_labels: True
run_paths_of_merges: True
run_features_of_paths: True
run_random_forest: False

remove_small_objects:
    bysize: 10000
    relabel: True

merge_adjacent_objects:
    seed: ~
    numberbysize: 0
    numberbyrandom: 10
    algorithm: pairs

compute_feature_images:
    anisotropy: [10, 1, 1]
    features:
        rawdata:
            raw: ~
            gauss_1:
                params: [1]
                func: gaussian
            gauss_3:
                params: [3]
                func: gaussian
            gauss_5:
                params: [5]
                func: gaussian
            gauss_10:
                params: [10]
                func: gaussian
        probs:
            raw: ~
            gauss_1:
                params: [1]
                func: gaussian
            gauss_3:
                params: [3]
                func: gaussian
            gauss_5:
                params: [5]
                func: gaussian
            gauss_10:
                params: [10]
                func: gaussian
        largeobj:
            disttransf:
                params: ~
                func: disttransf
                raw: ~
                gauss_1:
                    params: [1]
                    func: gaussian
                gauss_3:
                    params: [3]
                    func: gaussian
                gauss_5:
                    params: [5]
                    func: gaussian
                gauss_10:
                    params: [10]
                    func: gaussian
        largeobjm:
            disttransf:
                params: ~
                func: disttransf
                raw: ~
                gauss_1:
                    params: [1]
                    func: gaussian
                gauss_3:
                    params: [3]
                    func: gaussian
                gauss_5:
                    params: [5]
                    func: gaussian
                gauss_10:
                    params: [10]
                    func: gaussian

find_border_contacts: ~

paths_of_labels:
    penaltypower: 10
    ignorelabels: []
    max_end_count: 3
    max_end_count_seed: ~

paths_of_merges:
    penaltypower: 10
    ignorelabels: []
    max_end_count: 3
    max_end_count_seed: ~

features_of_paths:
    features:
        - Sum
        - Mean
        - Variance
        - Maximum
        - Minimum
        - Kurtosis
    max_paths_per_label: 5

random_forest: ~







