datafolder: '/mnt/localdata02/jhennies/neuraldata/cremi_2016/'
resultfolder: '/mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161111_random_forest_of_paths_add_features_develop/'
intermedfolder: '/mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161111_random_forest_of_paths_add_features_develop/intermediate/'
scriptsfolder: '/mnt/localdata02/jhennies/neuraldata/results/cremi_2016/161111_random_forest_of_paths_add_features_develop/scripts/'

createfolders: True
overwriteresults: True

rawdatafile:    'cremi.splA.raw_neurons.crop.split_xyz.h5'
rawdataname:    'raw'
labelsfile:     'cremi.splA.raw_neurons.crop.split_xyz.h5'
labelsname:     'neuron_ids'
largeobjfile:   'cremi.splA.raw_neurons.crop.split_xyz.largeobj.h5'
largeobjname:   'largeobj'
largeobjmfile:  'cremi.splA.raw_neurons.crop.split_xyz.largeobjm.h5'
largeobjmnames:
    - 'largeobjm'
    - 'mergeids_small'
    - 'mergeids_random'
    - 'mergeids_all'
    - 'change_hash'
locmaxborderfile:       'cremi.splA.raw_neurons.crop.split_xyz.locmaxborder.h5'
locmaxbordernames:
    - 'border_locmax'
    - 'border_locmax_m'
    - 'disttransf'
    - 'disttransfm'
bordercontactsfile:     'cremi.splA.raw_neurons.crop.split_xyz.bordercontacts.h5'
bordercontactsnames:
    - 'orphans'
    - 'orphansm'
    - 'onecontact'
    - 'onecontactm'
    - 'multiplecontact'
    - 'multiplecontactm'
locmaxfile:     'cremi.splA.raw_neurons.crop.split_xyz.locmax.h5'
locmaxnames:
    - 'locmax'
    - 'locmaxm'
pathstruefile:  'cremi.splA.raw_neurons.crop.split_xyz.paths.true.h5'
pathsfalsefile: 'cremi.splA.raw_neurons.crop.split_xyz.paths.false.h5'
featurefile:    'cremi.splA.raw_neurons.crop.split_xyz.features.h5'
randforestfile: 'cremi.splA.raw_neurons.crop.split_xyz.randforest.h5'

run_remove_small_objects: True
run_merge_adjacent_objects: False

remove_small_objects:
    bysize: 10000
    relabel: True

merge_adjacent_objects:
    seed: None
    numberbysize: 0
    numberbyrandom: 15

find_border_contacts:
    anisotropy: [10, 1, 1]
    return_bordercontact_images: False

localmax_on_disttransf:
    anisotropy: [10, 1, 1]
    sigma: 20

paths_within_labels:
    ignore: []
    penaltypower: 10
    max_paths_per_label: 20

paths_of_partners:
    ignore: []
    penaltypower: 10
    max_paths_per_label: 20

features_of_paths:
    anisotropy: [10, 1, 1]
    radius_paths_ends: 10
    features:
        - 'Sum'
        - 'Skewness'
        - 'Variance'
        - 'Mean'
        - 'Count'
        - 'Maximum'
        - 'Minimum'
    max_paths_per_label_true: 5
    max_paths_per_label_false: 10


