datafolder: '/media/julian/Daten/neuraldata/cremi_2016/'
resultfolder: '/media/julian/Daten/neuraldata/cremi_2016/develop/161011_locmax_paths_feature_extraction/'
intermedfolder: '/media/julian/Daten/neuraldata/cremi_2016/develop/161011_locmax_paths_feature_extraction/intermediate/'
createfolders: True

labelsfile:     'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.h5'
labelsname:     'labels'
largeobjfile:   'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.largeobjects.h5'
largeobjname:   'largeobjects'
largeobjmfile:  'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.largeobjmerged.h5'
largeobjmnames:
    - 'largeobjects_merged'
    - 'mergeids_small'
    - 'mergeids_random'
    - 'mergeids_all'
locmaxfile:     'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.locmax.h5'
locmaxnames:
    - 'disttransf'
    - 'disttransfm'
    - 'locmax'
    - 'locmaxm'
pathstruefile:  'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.paths.true.h5'
pathsfalsefile: 'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.paths.false.h5'
featurefile:    'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.features.h5'

merge_adjacent_objects:
    numberbysize: 10
    numberbyrandom: 5

localmax_on_disttransf:
    anisotropy: [10, 1, 1]
    sigma: 20

paths_within_labels:
    penaltypower: 10

paths_of_partners:
    penaltypower: 10

features_of_paths:
    anisotropy: [10, 1, 1]
    radius_paths_ends: 10
