datafolder: '/media/julian/Daten/neuraldata/cremi_2016/'
labelfile: 'cremi.splA.raw_neurons.crop.crop_10-200-200_110-712-712.largeobjects.h5'
labelname: 'largeobjects'
resultfolder: '/media/julian/Daten/neuraldata/cremi_2016/develop/161005_locmax_paths_feature_extraction/'
intermedfolder: '/media/julian/Daten/neuraldata/cremi_2016/develop/161005_locmax_paths_feature_extraction/intermediate/'
createfolders: True

merge_adjacent_objects:
    numberbysize: 10
    numberbyrandom: 10
